export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";
export const RESET_SEARCH = "RESET_SEARCH";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const SUCCESSFUL_LAUNCH = "SUCCESSFUL_LAUNCH";
export const SUCCESSFUL_LAING = "SUCCESSFUL_YEAR";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
